{
  "uid" : "73edc19a25d646f6",
  "name" : "test_t_case008",
  "fullName" : "test_proj.test_index_3#test_t_case008",
  "historyId" : "e494c20f2411125ffa3d93b45247e426",
  "time" : {
    "start" : 1626935282071,
    "stop" : 1626935290873,
    "duration" : 8802
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'data/a008.txt'",
  "statusTrace" : "def test_t_case008():\n        time.sleep(5)\n>       import test_tcA008 as tc08\n\ntest_proj/test_index_3.py:89: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n<frozen importlib._bootstrap>:1007: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:986: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:680: in _load_unlocked\n    ???\n/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:170: in exec_module\n    exec(co, module.__dict__)\ntest_proj/test_tcA008.py:45: in <module>\n    comments_text = test_comment_text()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def test_comment_text():\n>       with open('data/a008.txt', 'r', encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data/a008.txt'\n\ntest_proj/test_tcA008.py:28: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'data/a008.txt'",
    "statusTrace" : "def test_t_case008():\n        time.sleep(5)\n>       import test_tcA008 as tc08\n\ntest_proj/test_index_3.py:89: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n<frozen importlib._bootstrap>:1007: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:986: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:680: in _load_unlocked\n    ???\n/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:170: in exec_module\n    exec(co, module.__dict__)\ntest_proj/test_tcA008.py:45: in <module>\n    comments_text = test_comment_text()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def test_comment_text():\n>       with open('data/a008.txt', 'r', encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data/a008.txt'\n\ntest_proj/test_tcA008.py:28: FileNotFoundError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "e5d51563ea4a8d70",
      "name" : "log",
      "source" : "e5d51563ea4a8d70.txt",
      "type" : "text/plain",
      "size" : 344
    }, {
      "uid" : "b90063c386d09ec4",
      "name" : "stderr",
      "source" : "b90063c386d09ec4.txt",
      "type" : "text/plain",
      "size" : 215
    } ],
    "parameters" : [ ],
    "shouldDisplayMessage" : true,
    "hasContent" : true,
    "stepsCount" : 0,
    "attachmentsCount" : 2
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test_proj"
  }, {
    "name" : "suite",
    "value" : "test_index_3"
  }, {
    "name" : "host",
    "value" : "fv-az83-172"
  }, {
    "name" : "thread",
    "value" : "4168-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_proj.test_index_3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "73edc19a25d646f6.json",
  "parameterValues" : [ ]
}